/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthDashboardRouteRouteImport } from './routes/_auth/dashboard/route'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/dashboard/index'
import { Route as AuthDashboardProfileRouteImport } from './routes/_auth/dashboard/profile'
import { Route as AuthDashboardNotFoundRouteImport } from './routes/_auth/dashboard/not-found'
import { Route as AuthDashboardHomeRouteImport } from './routes/_auth/dashboard/home'
import { Route as AuthDashboardCalendarRouteImport } from './routes/_auth/dashboard/calendar'
import { Route as AuthDashboardStudySessionsIndexRouteImport } from './routes/_auth/dashboard/study-sessions/index'
import { Route as AuthDashboardResourcesIndexRouteImport } from './routes/_auth/dashboard/resources/index'
import { Route as AuthDashboardQuizzesIndexRouteImport } from './routes/_auth/dashboard/quizzes/index'
import { Route as AuthDashboardStudySessionsCreateRouteImport } from './routes/_auth/dashboard/study-sessions/create'
import { Route as AuthDashboardStudySessionsSessionIdIndexRouteImport } from './routes/_auth/dashboard/study-sessions/$sessionId/index'
import { Route as AuthDashboardQuizzesQuizIdIndexRouteImport } from './routes/_auth/dashboard/quizzes/$quizId/index'
import { Route as AuthDashboardQuizzesQuizIdAttemptsAttemptIdRouteImport } from './routes/_auth/dashboard/quizzes/$quizId/attempts/$attemptId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRouteRoute = AuthDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)
const AuthDashboardProfileRoute = AuthDashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)
const AuthDashboardNotFoundRoute = AuthDashboardNotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)
const AuthDashboardHomeRoute = AuthDashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)
const AuthDashboardCalendarRoute = AuthDashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)
const AuthDashboardStudySessionsIndexRoute =
  AuthDashboardStudySessionsIndexRouteImport.update({
    id: '/study-sessions/',
    path: '/study-sessions/',
    getParentRoute: () => AuthDashboardRouteRoute,
  } as any)
const AuthDashboardResourcesIndexRoute =
  AuthDashboardResourcesIndexRouteImport.update({
    id: '/resources/',
    path: '/resources/',
    getParentRoute: () => AuthDashboardRouteRoute,
  } as any)
const AuthDashboardQuizzesIndexRoute =
  AuthDashboardQuizzesIndexRouteImport.update({
    id: '/quizzes/',
    path: '/quizzes/',
    getParentRoute: () => AuthDashboardRouteRoute,
  } as any)
const AuthDashboardStudySessionsCreateRoute =
  AuthDashboardStudySessionsCreateRouteImport.update({
    id: '/study-sessions/create',
    path: '/study-sessions/create',
    getParentRoute: () => AuthDashboardRouteRoute,
  } as any)
const AuthDashboardStudySessionsSessionIdIndexRoute =
  AuthDashboardStudySessionsSessionIdIndexRouteImport.update({
    id: '/study-sessions/$sessionId/',
    path: '/study-sessions/$sessionId/',
    getParentRoute: () => AuthDashboardRouteRoute,
  } as any)
const AuthDashboardQuizzesQuizIdIndexRoute =
  AuthDashboardQuizzesQuizIdIndexRouteImport.update({
    id: '/quizzes/$quizId/',
    path: '/quizzes/$quizId/',
    getParentRoute: () => AuthDashboardRouteRoute,
  } as any)
const AuthDashboardQuizzesQuizIdAttemptsAttemptIdRoute =
  AuthDashboardQuizzesQuizIdAttemptsAttemptIdRouteImport.update({
    id: '/quizzes/$quizId/attempts/$attemptId',
    path: '/quizzes/$quizId/attempts/$attemptId',
    getParentRoute: () => AuthDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthDashboardRouteRouteWithChildren
  '/dashboard/calendar': typeof AuthDashboardCalendarRoute
  '/dashboard/home': typeof AuthDashboardHomeRoute
  '/dashboard/not-found': typeof AuthDashboardNotFoundRoute
  '/dashboard/profile': typeof AuthDashboardProfileRoute
  '/dashboard/': typeof AuthDashboardIndexRoute
  '/dashboard/study-sessions/create': typeof AuthDashboardStudySessionsCreateRoute
  '/dashboard/quizzes': typeof AuthDashboardQuizzesIndexRoute
  '/dashboard/resources': typeof AuthDashboardResourcesIndexRoute
  '/dashboard/study-sessions': typeof AuthDashboardStudySessionsIndexRoute
  '/dashboard/quizzes/$quizId': typeof AuthDashboardQuizzesQuizIdIndexRoute
  '/dashboard/study-sessions/$sessionId': typeof AuthDashboardStudySessionsSessionIdIndexRoute
  '/dashboard/quizzes/$quizId/attempts/$attemptId': typeof AuthDashboardQuizzesQuizIdAttemptsAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard/calendar': typeof AuthDashboardCalendarRoute
  '/dashboard/home': typeof AuthDashboardHomeRoute
  '/dashboard/not-found': typeof AuthDashboardNotFoundRoute
  '/dashboard/profile': typeof AuthDashboardProfileRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/dashboard/study-sessions/create': typeof AuthDashboardStudySessionsCreateRoute
  '/dashboard/quizzes': typeof AuthDashboardQuizzesIndexRoute
  '/dashboard/resources': typeof AuthDashboardResourcesIndexRoute
  '/dashboard/study-sessions': typeof AuthDashboardStudySessionsIndexRoute
  '/dashboard/quizzes/$quizId': typeof AuthDashboardQuizzesQuizIdIndexRoute
  '/dashboard/study-sessions/$sessionId': typeof AuthDashboardStudySessionsSessionIdIndexRoute
  '/dashboard/quizzes/$quizId/attempts/$attemptId': typeof AuthDashboardQuizzesQuizIdAttemptsAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_auth/dashboard': typeof AuthDashboardRouteRouteWithChildren
  '/_auth/dashboard/calendar': typeof AuthDashboardCalendarRoute
  '/_auth/dashboard/home': typeof AuthDashboardHomeRoute
  '/_auth/dashboard/not-found': typeof AuthDashboardNotFoundRoute
  '/_auth/dashboard/profile': typeof AuthDashboardProfileRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/dashboard/study-sessions/create': typeof AuthDashboardStudySessionsCreateRoute
  '/_auth/dashboard/quizzes/': typeof AuthDashboardQuizzesIndexRoute
  '/_auth/dashboard/resources/': typeof AuthDashboardResourcesIndexRoute
  '/_auth/dashboard/study-sessions/': typeof AuthDashboardStudySessionsIndexRoute
  '/_auth/dashboard/quizzes/$quizId/': typeof AuthDashboardQuizzesQuizIdIndexRoute
  '/_auth/dashboard/study-sessions/$sessionId/': typeof AuthDashboardStudySessionsSessionIdIndexRoute
  '/_auth/dashboard/quizzes/$quizId/attempts/$attemptId': typeof AuthDashboardQuizzesQuizIdAttemptsAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/dashboard'
    | '/dashboard/calendar'
    | '/dashboard/home'
    | '/dashboard/not-found'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/dashboard/study-sessions/create'
    | '/dashboard/quizzes'
    | '/dashboard/resources'
    | '/dashboard/study-sessions'
    | '/dashboard/quizzes/$quizId'
    | '/dashboard/study-sessions/$sessionId'
    | '/dashboard/quizzes/$quizId/attempts/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/dashboard/calendar'
    | '/dashboard/home'
    | '/dashboard/not-found'
    | '/dashboard/profile'
    | '/dashboard'
    | '/dashboard/study-sessions/create'
    | '/dashboard/quizzes'
    | '/dashboard/resources'
    | '/dashboard/study-sessions'
    | '/dashboard/quizzes/$quizId'
    | '/dashboard/study-sessions/$sessionId'
    | '/dashboard/quizzes/$quizId/attempts/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/_auth/dashboard'
    | '/_auth/dashboard/calendar'
    | '/_auth/dashboard/home'
    | '/_auth/dashboard/not-found'
    | '/_auth/dashboard/profile'
    | '/_auth/dashboard/'
    | '/_auth/dashboard/study-sessions/create'
    | '/_auth/dashboard/quizzes/'
    | '/_auth/dashboard/resources/'
    | '/_auth/dashboard/study-sessions/'
    | '/_auth/dashboard/quizzes/$quizId/'
    | '/_auth/dashboard/study-sessions/$sessionId/'
    | '/_auth/dashboard/quizzes/$quizId/attempts/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/profile': {
      id: '/_auth/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthDashboardProfileRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/not-found': {
      id: '/_auth/dashboard/not-found'
      path: '/not-found'
      fullPath: '/dashboard/not-found'
      preLoaderRoute: typeof AuthDashboardNotFoundRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/home': {
      id: '/_auth/dashboard/home'
      path: '/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof AuthDashboardHomeRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/calendar': {
      id: '/_auth/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof AuthDashboardCalendarRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/study-sessions/': {
      id: '/_auth/dashboard/study-sessions/'
      path: '/study-sessions'
      fullPath: '/dashboard/study-sessions'
      preLoaderRoute: typeof AuthDashboardStudySessionsIndexRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/resources/': {
      id: '/_auth/dashboard/resources/'
      path: '/resources'
      fullPath: '/dashboard/resources'
      preLoaderRoute: typeof AuthDashboardResourcesIndexRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/quizzes/': {
      id: '/_auth/dashboard/quizzes/'
      path: '/quizzes'
      fullPath: '/dashboard/quizzes'
      preLoaderRoute: typeof AuthDashboardQuizzesIndexRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/study-sessions/create': {
      id: '/_auth/dashboard/study-sessions/create'
      path: '/study-sessions/create'
      fullPath: '/dashboard/study-sessions/create'
      preLoaderRoute: typeof AuthDashboardStudySessionsCreateRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/study-sessions/$sessionId/': {
      id: '/_auth/dashboard/study-sessions/$sessionId/'
      path: '/study-sessions/$sessionId'
      fullPath: '/dashboard/study-sessions/$sessionId'
      preLoaderRoute: typeof AuthDashboardStudySessionsSessionIdIndexRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/quizzes/$quizId/': {
      id: '/_auth/dashboard/quizzes/$quizId/'
      path: '/quizzes/$quizId'
      fullPath: '/dashboard/quizzes/$quizId'
      preLoaderRoute: typeof AuthDashboardQuizzesQuizIdIndexRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/quizzes/$quizId/attempts/$attemptId': {
      id: '/_auth/dashboard/quizzes/$quizId/attempts/$attemptId'
      path: '/quizzes/$quizId/attempts/$attemptId'
      fullPath: '/dashboard/quizzes/$quizId/attempts/$attemptId'
      preLoaderRoute: typeof AuthDashboardQuizzesQuizIdAttemptsAttemptIdRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
  }
}

interface AuthDashboardRouteRouteChildren {
  AuthDashboardCalendarRoute: typeof AuthDashboardCalendarRoute
  AuthDashboardHomeRoute: typeof AuthDashboardHomeRoute
  AuthDashboardNotFoundRoute: typeof AuthDashboardNotFoundRoute
  AuthDashboardProfileRoute: typeof AuthDashboardProfileRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
  AuthDashboardStudySessionsCreateRoute: typeof AuthDashboardStudySessionsCreateRoute
  AuthDashboardQuizzesIndexRoute: typeof AuthDashboardQuizzesIndexRoute
  AuthDashboardResourcesIndexRoute: typeof AuthDashboardResourcesIndexRoute
  AuthDashboardStudySessionsIndexRoute: typeof AuthDashboardStudySessionsIndexRoute
  AuthDashboardQuizzesQuizIdIndexRoute: typeof AuthDashboardQuizzesQuizIdIndexRoute
  AuthDashboardStudySessionsSessionIdIndexRoute: typeof AuthDashboardStudySessionsSessionIdIndexRoute
  AuthDashboardQuizzesQuizIdAttemptsAttemptIdRoute: typeof AuthDashboardQuizzesQuizIdAttemptsAttemptIdRoute
}

const AuthDashboardRouteRouteChildren: AuthDashboardRouteRouteChildren = {
  AuthDashboardCalendarRoute: AuthDashboardCalendarRoute,
  AuthDashboardHomeRoute: AuthDashboardHomeRoute,
  AuthDashboardNotFoundRoute: AuthDashboardNotFoundRoute,
  AuthDashboardProfileRoute: AuthDashboardProfileRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
  AuthDashboardStudySessionsCreateRoute: AuthDashboardStudySessionsCreateRoute,
  AuthDashboardQuizzesIndexRoute: AuthDashboardQuizzesIndexRoute,
  AuthDashboardResourcesIndexRoute: AuthDashboardResourcesIndexRoute,
  AuthDashboardStudySessionsIndexRoute: AuthDashboardStudySessionsIndexRoute,
  AuthDashboardQuizzesQuizIdIndexRoute: AuthDashboardQuizzesQuizIdIndexRoute,
  AuthDashboardStudySessionsSessionIdIndexRoute:
    AuthDashboardStudySessionsSessionIdIndexRoute,
  AuthDashboardQuizzesQuizIdAttemptsAttemptIdRoute:
    AuthDashboardQuizzesQuizIdAttemptsAttemptIdRoute,
}

const AuthDashboardRouteRouteWithChildren =
  AuthDashboardRouteRoute._addFileChildren(AuthDashboardRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthDashboardRouteRoute: typeof AuthDashboardRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthDashboardRouteRoute: AuthDashboardRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
