/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardNotFoundRouteImport } from './routes/dashboard/not-found'
import { Route as DashboardHomeRouteImport } from './routes/dashboard/home'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard/calendar'
import { Route as DashboardStudySessionsIndexRouteImport } from './routes/dashboard/study-sessions/index'
import { Route as DashboardResourcesIndexRouteImport } from './routes/dashboard/resources/index'
import { Route as DashboardQuizzesIndexRouteImport } from './routes/dashboard/quizzes/index'
import { Route as DashboardStudySessionsCreateRouteImport } from './routes/dashboard/study-sessions/create'
import { Route as DashboardStudySessionsSessionIdIndexRouteImport } from './routes/dashboard/study-sessions/$sessionId/index'
import { Route as DashboardQuizzesQuizIdIndexRouteImport } from './routes/dashboard/quizzes/$quizId/index'
import { Route as DashboardQuizzesQuizIdAttemptsAttemptIdRouteImport } from './routes/dashboard/quizzes/$quizId/attempts/$attemptId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNotFoundRoute = DashboardNotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardStudySessionsIndexRoute =
  DashboardStudySessionsIndexRouteImport.update({
    id: '/study-sessions/',
    path: '/study-sessions/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardResourcesIndexRoute = DashboardResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardQuizzesIndexRoute = DashboardQuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardStudySessionsCreateRoute =
  DashboardStudySessionsCreateRouteImport.update({
    id: '/study-sessions/create',
    path: '/study-sessions/create',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardStudySessionsSessionIdIndexRoute =
  DashboardStudySessionsSessionIdIndexRouteImport.update({
    id: '/study-sessions/$sessionId/',
    path: '/study-sessions/$sessionId/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardQuizzesQuizIdIndexRoute =
  DashboardQuizzesQuizIdIndexRouteImport.update({
    id: '/quizzes/$quizId/',
    path: '/quizzes/$quizId/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardQuizzesQuizIdAttemptsAttemptIdRoute =
  DashboardQuizzesQuizIdAttemptsAttemptIdRouteImport.update({
    id: '/quizzes/$quizId/attempts/$attemptId',
    path: '/quizzes/$quizId/attempts/$attemptId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/not-found': typeof DashboardNotFoundRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/study-sessions/create': typeof DashboardStudySessionsCreateRoute
  '/dashboard/quizzes': typeof DashboardQuizzesIndexRoute
  '/dashboard/resources': typeof DashboardResourcesIndexRoute
  '/dashboard/study-sessions': typeof DashboardStudySessionsIndexRoute
  '/dashboard/quizzes/$quizId': typeof DashboardQuizzesQuizIdIndexRoute
  '/dashboard/study-sessions/$sessionId': typeof DashboardStudySessionsSessionIdIndexRoute
  '/dashboard/quizzes/$quizId/attempts/$attemptId': typeof DashboardQuizzesQuizIdAttemptsAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/not-found': typeof DashboardNotFoundRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/study-sessions/create': typeof DashboardStudySessionsCreateRoute
  '/dashboard/quizzes': typeof DashboardQuizzesIndexRoute
  '/dashboard/resources': typeof DashboardResourcesIndexRoute
  '/dashboard/study-sessions': typeof DashboardStudySessionsIndexRoute
  '/dashboard/quizzes/$quizId': typeof DashboardQuizzesQuizIdIndexRoute
  '/dashboard/study-sessions/$sessionId': typeof DashboardStudySessionsSessionIdIndexRoute
  '/dashboard/quizzes/$quizId/attempts/$attemptId': typeof DashboardQuizzesQuizIdAttemptsAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/not-found': typeof DashboardNotFoundRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/study-sessions/create': typeof DashboardStudySessionsCreateRoute
  '/dashboard/quizzes/': typeof DashboardQuizzesIndexRoute
  '/dashboard/resources/': typeof DashboardResourcesIndexRoute
  '/dashboard/study-sessions/': typeof DashboardStudySessionsIndexRoute
  '/dashboard/quizzes/$quizId/': typeof DashboardQuizzesQuizIdIndexRoute
  '/dashboard/study-sessions/$sessionId/': typeof DashboardStudySessionsSessionIdIndexRoute
  '/dashboard/quizzes/$quizId/attempts/$attemptId': typeof DashboardQuizzesQuizIdAttemptsAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/calendar'
    | '/dashboard/home'
    | '/dashboard/not-found'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/study-sessions/create'
    | '/dashboard/quizzes'
    | '/dashboard/resources'
    | '/dashboard/study-sessions'
    | '/dashboard/quizzes/$quizId'
    | '/dashboard/study-sessions/$sessionId'
    | '/dashboard/quizzes/$quizId/attempts/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard/calendar'
    | '/dashboard/home'
    | '/dashboard/not-found'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/study-sessions/create'
    | '/dashboard/quizzes'
    | '/dashboard/resources'
    | '/dashboard/study-sessions'
    | '/dashboard/quizzes/$quizId'
    | '/dashboard/study-sessions/$sessionId'
    | '/dashboard/quizzes/$quizId/attempts/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/calendar'
    | '/dashboard/home'
    | '/dashboard/not-found'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/study-sessions/create'
    | '/dashboard/quizzes/'
    | '/dashboard/resources/'
    | '/dashboard/study-sessions/'
    | '/dashboard/quizzes/$quizId/'
    | '/dashboard/study-sessions/$sessionId/'
    | '/dashboard/quizzes/$quizId/attempts/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/not-found': {
      id: '/dashboard/not-found'
      path: '/not-found'
      fullPath: '/dashboard/not-found'
      preLoaderRoute: typeof DashboardNotFoundRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/home': {
      id: '/dashboard/home'
      path: '/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/study-sessions/': {
      id: '/dashboard/study-sessions/'
      path: '/study-sessions'
      fullPath: '/dashboard/study-sessions'
      preLoaderRoute: typeof DashboardStudySessionsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/resources/': {
      id: '/dashboard/resources/'
      path: '/resources'
      fullPath: '/dashboard/resources'
      preLoaderRoute: typeof DashboardResourcesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/quizzes/': {
      id: '/dashboard/quizzes/'
      path: '/quizzes'
      fullPath: '/dashboard/quizzes'
      preLoaderRoute: typeof DashboardQuizzesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/study-sessions/create': {
      id: '/dashboard/study-sessions/create'
      path: '/study-sessions/create'
      fullPath: '/dashboard/study-sessions/create'
      preLoaderRoute: typeof DashboardStudySessionsCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/study-sessions/$sessionId/': {
      id: '/dashboard/study-sessions/$sessionId/'
      path: '/study-sessions/$sessionId'
      fullPath: '/dashboard/study-sessions/$sessionId'
      preLoaderRoute: typeof DashboardStudySessionsSessionIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/quizzes/$quizId/': {
      id: '/dashboard/quizzes/$quizId/'
      path: '/quizzes/$quizId'
      fullPath: '/dashboard/quizzes/$quizId'
      preLoaderRoute: typeof DashboardQuizzesQuizIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/quizzes/$quizId/attempts/$attemptId': {
      id: '/dashboard/quizzes/$quizId/attempts/$attemptId'
      path: '/quizzes/$quizId/attempts/$attemptId'
      fullPath: '/dashboard/quizzes/$quizId/attempts/$attemptId'
      preLoaderRoute: typeof DashboardQuizzesQuizIdAttemptsAttemptIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardNotFoundRoute: typeof DashboardNotFoundRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardStudySessionsCreateRoute: typeof DashboardStudySessionsCreateRoute
  DashboardQuizzesIndexRoute: typeof DashboardQuizzesIndexRoute
  DashboardResourcesIndexRoute: typeof DashboardResourcesIndexRoute
  DashboardStudySessionsIndexRoute: typeof DashboardStudySessionsIndexRoute
  DashboardQuizzesQuizIdIndexRoute: typeof DashboardQuizzesQuizIdIndexRoute
  DashboardStudySessionsSessionIdIndexRoute: typeof DashboardStudySessionsSessionIdIndexRoute
  DashboardQuizzesQuizIdAttemptsAttemptIdRoute: typeof DashboardQuizzesQuizIdAttemptsAttemptIdRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardNotFoundRoute: DashboardNotFoundRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardStudySessionsCreateRoute: DashboardStudySessionsCreateRoute,
  DashboardQuizzesIndexRoute: DashboardQuizzesIndexRoute,
  DashboardResourcesIndexRoute: DashboardResourcesIndexRoute,
  DashboardStudySessionsIndexRoute: DashboardStudySessionsIndexRoute,
  DashboardQuizzesQuizIdIndexRoute: DashboardQuizzesQuizIdIndexRoute,
  DashboardStudySessionsSessionIdIndexRoute:
    DashboardStudySessionsSessionIdIndexRoute,
  DashboardQuizzesQuizIdAttemptsAttemptIdRoute:
    DashboardQuizzesQuizIdAttemptsAttemptIdRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
